### ISSUE TITLE
 top-up valve not working

### ISSUE THREAD

**Issue by eugenikus8** [heinwessels/factorio-valves#6]
mod: 1.1.1 
Factorio: 2.0.19 

The valve does not allow fluids to pass through at any threshold

![2024-11-16_031211](https://github.com/user-attachments/assets/6070550d-866a-4813-8379-1bbd80f725d6)

![2024-11-16_031217](https://github.com/user-attachments/assets/0c678649-bcb8-4667-aef3-43cde54bc217)

![2024-11-16_031225](https://github.com/user-attachments/assets/aee80d34-ff11-4524-8edd-2ced71a9f90b)

**Comment by heinwessels** [comment]
Is that a new valve you placed after the update? Or an pre-existing valve?

If this was a pre-existing valve then it should be fixed by f18b5b27fea81afc3ac7b32ec33eff4af4b20816, which I just released. Otherwise please tell me exact reproduction steps.

Thanks for the report!

**Comment by eugenikus8** [comment]
I tried it on the new version 1.1.2. Nothing has changed. I deleted, changed the threshold in it. Bottom line: the top-up valve doesn't work.
