### ISSUE TITLE
[1.1.2] top-up valve doesn't work

### ISSUE THREAD

**Issue by eugenikus8** [heinwessels/factorio-valves#7]
I tried it on the new version 1.1.2. Nothing has changed. I deleted it and rebuilt it, deleted and hit the back button, changed the threshold in it. I tried to create a new game. Bottom line: the top-up valve doesn't work.

**Comment by eugenikus8** [comment]
By the way, the directional arrow (as in the pump) is now drawn correctly in the overflow valve. Other valves do not have it at all.

**Comment by heinwessels** [comment]
Ah, I see now. An edge case I didn't test. 

> By the way, the directional arrow (as in the pump) is now drawn correctly in the overflow valve. Other valves do not have it at all.
Yeah this is because of me reducing the amount of entities. The overflow valve's internal pump's output is now part of the pump, so the pump's regular arrow is being drawn. I'm still trying to get API changes to make it uniform.

Ref: #6

**Comment by heinwessels** [comment]
Should be fixed now. It was only broken when the output pipe was empty. Fixed in 8f8e46b
