### ISSUE TITLE
Thank you. Now everything works

### ISSUE THREAD

**Issue by eugenikus8** [heinwessels/factorio-valves#8]
This may not be a bug. But if you set the top-up valve threshold: 0, then in the end there will be 5 fluids in the pipe, if 10, then there will be 20 fluids in the pipe, not 10. Why is that?

**Comment by eugenikus8** [comment]
I also noticed a bug. Overflow valve with thresholds 100 does not allow fluids to pass through.

**Comment by heinwessels** [comment]
Great that it works! That's due to the one-tick delay in the circuit network. So it pumps one tick longer than it should, which looks big in a pipe's small fluidbox. A better test is to connect it to a storage tank.

**Comment by heinwessels** [comment]
> I also noticed a bug. Overflow valve with threshold 100 does not allow fluids to pass through.

Not a bug. It only allows flow when input is bigger than the threshold. For example, if I put a 80% overflow valve on a tank, then I would expect it to always maintain 80% in the tank.
